### ISSUE TITLE
libmpv doesn't respect configuration file changes

### ISSUE THREAD

**Issue by tranzystorekk** [kohsine/libmpv2-rs#2]
I am trying to force the underlying libmpv to set `ao = pulse` on WSL2, but the changes in my `~/.config/mpv/mpv.conf` file don't seem to be respected.

More specifically, mpv on my WSL2 system tries to use the pipewire driver by default, which leads to libpipewire printing out ugly warnings that mess with TUI controls. I can force regular `mpv` to use `ao=pulse`, but libmpv2-rs seemingly ignores that, even if I put that option under the `[libmpv]` section.

**Comment by kohsine** [comment]
That's the default behavior of libmpv. https://github.com/mpv-player/mpv/blob/541e00fcdb2b44bb164be65647171ce49869a6cf/libmpv/client.h#L447

Set `config=yes` if you want libmpv to read your config file.

**Comment by tranzystorekk** [comment]
Thank you, doing `Mpv::with_initializer(|init| { init.set_option("config", "yes") })` fixes it for me!
